### ISSUE TITLE
Main connector pinout

### ISSUE THREAD

**Issue by rusefillc** [opelpanfan/car-dash-7#1]
12v power and CAN at least :)

**Comment by opelpanfan** [comment]
updated main page with connector pinouts

**Comment by rusefillc** [comment]
please clarify relationship between VIN and VIN_BAT

i.e. which one do I connect? both? not both?

**Comment by opelpanfan** [comment]
VIN is to power screen, VIN_BAT provides separate +12V to 16 HIGH side outputs through screw terminal in the middle.

**Comment by opelpanfan** [comment]
https://opelpanfan.github.io/car-dash-7/pinout/
